import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { colors, spacing, fontSize } from "../../constants/theme";

export default function LegalScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.safe}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} hitSlop={10}>
          <Ionicons name="chevron-back" size={24} color={colors.text} />
        </TouchableOpacity>
        <Text style={styles.title}>Terms & Privacy</Text>
        <View style={{ width: 24 }} />
      </View>

      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.h1}>Terms of Service</Text>
        <Text style={styles.muted}>Last updated: 2026</Text>

        <Text style={styles.h2}>1. Acceptance</Text>
        <Text style={styles.body}>
          By using Boss Mode, you accept these terms. If you do not agree, do
          not use the app.
        </Text>

        <Text style={styles.h2}>2. The Service</Text>
        <Text style={styles.body}>
          Boss Mode is an accountability commitment device. You voluntarily set
          deadlines for tasks and authorise the app to charge you when you miss
          them. Charges are not refundable except in cases of demonstrable
          system error.
        </Text>

        <Text style={styles.h2}>3. Penalties as Commitment Contracts</Text>
        <Text style={styles.body}>
          Penalty charges are commitment contracts you make with yourself,
          payable to a third party (charity or partner). Boss Mode is not the
          recipient of penalty payments. Boss Mode is not a gambling product.
        </Text>

        <Text style={styles.h2}>4. Subscription</Text>
        <Text style={styles.body}>
          Pro and VIP tiers are billed monthly. Cancellation stops further
          billing immediately; access continues until the end of the paid
          period.
        </Text>

        <Text style={styles.h2}>5. AI-Generated Content</Text>
        <Text style={styles.body}>
          Boss messages and performance reviews are generated by AI
          (Anthropic Claude) and may contain inaccuracies. Boss Mode is not
          liable for AI output.
        </Text>

        <Text style={[styles.h1, { marginTop: spacing.xl }]}>
          Privacy Policy
        </Text>
        <Text style={styles.muted}>Last updated: 2026</Text>

        <Text style={styles.h2}>What we collect</Text>
        <Text style={styles.body}>
          - Account info via Clerk: email, name, optional avatar{"\n"}
          - Your tasks, projects, goals, check-in responses, and chat history{"\n"}
          - Payment info via Stripe (we never see card numbers){"\n"}
          - Usage analytics (page views, feature use)
        </Text>

        <Text style={styles.h2}>How we use it</Text>
        <Text style={styles.body}>
          - To run the service (assign tasks, send check-ins, charge
          penalties){"\n"}
          - AI Boss responses send context to Anthropic; they do not store it
          for training{"\n"}
          - Partner data is shared only with active accountability partners
          you invite
        </Text>

        <Text style={styles.h2}>Your rights</Text>
        <Text style={styles.body}>
          You can export or delete all your data at any time. Email
          support@bossmode.app to request deletion. We comply with GDPR and
          CCPA.
        </Text>

        <Text style={styles.h2}>Third parties</Text>
        <Text style={styles.body}>
          Clerk (auth), Convex (database/backend), Stripe (payments),
          Anthropic (AI). All process data on our behalf under standard data
          processing agreements.
        </Text>

        <Text style={styles.h2}>Contact</Text>
        <Text style={styles.body}>
          Privacy questions: privacy@bossmode.app
        </Text>

        <View style={{ height: spacing.xxl }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  title: { color: colors.text, fontSize: fontSize.lg, fontWeight: "700" },
  content: { padding: spacing.lg, gap: spacing.sm },
  h1: { color: colors.text, fontSize: fontSize.xl, fontWeight: "800" },
  h2: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: "700",
    marginTop: spacing.md,
  },
  body: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    lineHeight: 22,
  },
  muted: { color: colors.textMuted, fontSize: fontSize.xs, fontStyle: "italic" },
});
